version: '3.7'

services:
    minio:
        image: minio/minio:latest
        ports:
            - 9000:9000
            - 10001:10001
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio_pass
        entrypoint: bash -c 'mkdir -p /data/test-bucket{1..3} && /opt/bin/minio server /data --console-address ":10001"'
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:10001/minio/health/live"
                ]
            interval: 30s
            timeout: 20s
            retries: 3
